### PR TITLE
Implement new on-disk format

### PR DESCRIPTION
**Pull request by effweh-ait**

### CODE REVIEW

**Comment by andreashappe** [comment]
Hi and thank you for the contribution! Could you add an additional commit with documentation (e.g., the new on-disk format, etc.)?

**Comment by andreashappe** [comment]
so this patch switches from an on-disk format that is fully defined (i.e., byte position of all different headers are well known) to a undefined on-disk format (i.e., backend vendor can implement it any way he wants as long as a key-value store is included)?

**Comment by effweh-ait** [comment]
Yes. In other words: it depends on the backend vendor implementing some kind of key-value store for "user-defined metadata" (as it is called in S3), but it does not depend on any specific implementation details (apart from certain, rather minimal, size requirements).

(The keys and possible values themselves, though, are of course defined and documented)

Though if the key-value-store is not available (or - for some inexplicable reason - unusable), the metadata could still be saved separately, for example as a JSON map. I've already implemented and successfully tested that in the on-disk backend of archistar-smc-tools (though not checked in yet because it depends on the new interface and would not build)

**Comment by andreashappe** [comment]
yes, as in "we do not have a well-specified on-disk format anymore" -> if you're depending upon the backend to store the data (as it is fit for them) we do not control the on-disk format anymore.

Please add some reasoning about that---and why we do not define a byte-level on-disk format--- to the documentation. This is the first question that an external person will ask if he opens the on-disk format documentation, so it should be answered in there.

**Comment by effweh-ait** [comment]
I added some explanations. Do you think this is sufficient?

**Pull request merged**
